version: '3.8'

services:
    openflap:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        volumes:
            - ..:/workspace
            - /dev/bus/usb:/dev/bus/usb
        device_cgroup_rules:
            - "c 188:* rmw"
            - 'c 189:* rmw'
        user: vscode
        command: sleep infinity