name: 'Generte Flaps' 
on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
      - master
    paths:
      - hardware/module/flaps/**
      - .devcontainer/gerbolyze/**
      - .github/workflows/hardware_validation.yml
  
env:
  CI_ARG: ${{ github.ref == 'refs/heads/main' && '' || '--dry-run' }}

jobs:
  validate_hardware_designs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
        # with:
          # fetch-depth: 0 # fetch all history for tags
          # fetch-tags: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate hardware design
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/gerbolyze/devcontainer.json
          imageName: ghcr.io/toonvaneyck/openflap-gerbolyze-devcontainer
          cacheFrom: ghcr.io/toonvaneyck/openflap-gerbolyze-devcontainer
          push: always
          runCmd: |
            cd hardware
            ./ci-script-gerbolyze.sh ${CI_ARG}
