name: 'Validate hardware designs' 
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      - hardware/module/side_panel/src/**
      - hardware/module/encoder_wheel/src/**
      - hardware/top_connector/src/**
      - hardware/controller/src/**
      - .devcontainer/ecad-mcad/**
      - .github/workflows/hardware_validation.yml
  
env:
  CI_ARG: ${{ github.ref == 'refs/heads/main' && '' || '--dry-run' }}  # Full run on main brach, dry-run on other branches

jobs:
  validate_hardware_designs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
        with:
          lfs: 'true'
          fetch-depth: 0 # fetch all history for tags
          fetch-tags: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate hardware design
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/ecad-mcad/devcontainer.json
          imageName: ghcr.io/toonvaneyck/openflap-ecad-mcad-devcontainer
          cacheFrom: ghcr.io/toonvaneyck/openflap-ecad-mcad-devcontainer
          push: always
          runCmd: |
            ./hardware/ci-script-kibot.sh ${CI_ARG}

      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add hardware/module/side_panel/*
          git add hardware/module/encoder_wheel/*
          git add hardware/top_connector/*
          git add hardware/controller/*
          git commit -m "Github Actions: Update schematic pdfs and pcb renders."
          git push

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hardware
          path: build/hardware/
