name: 'Validate and export hardware' 
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3
        with:
          fetch-tags: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/kibot/devcontainer.json
          skipContainerUserIdUpdate: false
          imageName: ghcr.io/toonvaneyck/openflap-kibot-devcontainer
          cacheFrom: ghcr.io/toonvaneyck/openflap-kibot-devcontainer
          push: always
          runCmd: |
            figlet -f 3d.flf Open Flap
            cd hardware
            ./ci-script.sh