name: "Experimenting with KiBot"

# Controls when the action will run.
on:
  push:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - '.github/workflows/kibot_action.yml'
  pull_request:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - '.github/workflows/kibot_action.yml'
  repository_dispatch:
    types: [run_gha]

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ERC:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run ERC
      uses: INTI-CMNB/KiBot@v2_k8
      with:
        config: hardware/module/side_panel/side_panel.kibot.yaml
        dir: Generated
        skip: run_drc
        targets: __NONE__

    - name: Retrieve results
      uses: actions/upload-artifact@v4
      with:
        name: ERC_Output
        path: Generated


  DRC:
    runs-on: ubuntu-latest
    needs: ERC

    steps:
    - uses: actions/checkout@v4

    - name: Run DRC
      uses: INTI-CMNB/KiBot@v2_k8
      with:
        config: hardware/module/side_panel/side_panel.kibot.yaml
        dir: Generated
        skip: run_erc
        targets: __NONE__

    - name: Retrieve results
      uses: actions/upload-artifact@v4
      with:
        name: DRC_Output
        path: Generated


  default:
    name: "Default variant"
    runs-on: ubuntu-latest
    needs: [ERC, DRC]

    steps:
    - uses: actions/checkout@v4

    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        config: hardware/module/side_panel/side_panel.kibot.yaml
        dir: default
        variant: default
        skip: run_erc,run_drc

    - name: upload results
      uses: actions/upload-artifact@v4
      with:
        name: default_variant
        path: default