name: 'Validate mechanical design' 
on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
      - master
    paths:
      - mechanical/**
      - .devcontainer/freecad/**
      - .github/workflows/mechanical_validation.yml
  
env:
  CI_ARG: ${{ github.ref == 'refs/heads/main' && '' || '--dry-run' }} # Full run on main brach, dry-run on other branches

jobs:
  validate_hardware_designs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
        with:
          lfs: 'true'
          fetch-depth: 1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate hardware design
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/freecad/devcontainer.json
          imageName: ghcr.io/toonvaneyck/openflap-freecad-devcontainer
          cacheFrom: ghcr.io/toonvaneyck/openflap-freecad-devcontainer
          push: always
          runCmd: |
            cd mechanical
            mkdir -p build
            ./ci-script-freecad.sh ${CI_ARG}
