name: Build and Push Container

on:
  workflow_call:
    inputs:
      container:
        description: 'The directory containing the Dockerfile, e.g.: ecad-mcad'
        required: true
        type: string
      tag:
        description: 'The tag of the image to build and push'
        required: true
        type: string

jobs:
  update_container_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: 'true'

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            container:
              - '.devcontainer/${{ inputs.container }}/**'

      - name: Login to GitHub Container Registry
        if: steps.changes.outputs.container == 'true'
        uses: docker/login-action@v3 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: steps.changes.outputs.container == 'true'
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/ecad-mcad/devcontainer.json
          imageName: ghcr.io/toonvaneyck/${{ inputs.container }}
          cacheFrom: ghcr.io/toonvaneyck/${{ inputs.container }}
          push: always